#==========================================================================
# Description: Build Armbian For Amlogic s9xxx tv box
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
#==========================================================================

name: Build armbian desktop

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_branch:
        description: "Branch: edge / current / legacy"
        required: false
        default: "edge"
      set_release:
        description: "Release: jammy / focal / bullseye"
        required: false
        default: "jammy"
      set_board:
        description: "Board: odroidn2 / lepotato"
        required: false
        default: "odroidn2"
      set_desktop:
        description: "Set desktop environment: xfce / budgie / cinnamon / gnome / xmonad / mate"
        required: false
        default: "xfce"
      armbian_soc:
        description: "Set Amlogic SoC."
        required: false
        default: "all"
      armbian_kernel:
        description: "Set kernel version."
        required: false
        default: "5.15.25_5.10.100"
      armbian_size:
        description: "Set armbian rootfs size."
        required: false
        default: "3584"
      armbian_fstype:
        description: "Set armbian rootfs type."
        required: false
        default: "ext4"

  #schedule:
    #- cron: "0 17 * * 0"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/compile-kernel/tools/script/ubuntu2204-build-armbian-depends)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "COMPILE_STARTINGTIME=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV
          ARR_BRANCH=("edge" "current" "legacy")
          set_branch="${{ github.event.inputs.set_branch }}"
          if  [[ -z "${set_branch}" || -z "$(echo "${ARR_BRANCH[@]}" | grep -w "${set_branch}")" ]]; then
              set_branch="current"
          fi
          echo "ARMBIAN_BRANCH=${set_branch}" >> $GITHUB_ENV
          ARR_RELEASE=("jammy" "focal" "bullseye")
          set_release="${{ github.event.inputs.set_release }}"
          if  [[ -z "${set_release}" || -z "$(echo "${ARR_RELEASE[@]}" | grep -w "${set_release}")" ]]; then
              set_release="focal"
          fi
          echo "ARMBIAN_RELEASE=${set_release}" >> $GITHUB_ENV
          ARR_BOARD=("lepotato" "odroidn2")
          set_board="${{ github.event.inputs.set_board }}"
          if  [[ -z "${set_board}" || -z "$(echo "${ARR_BOARD[@]}" | grep -w "${set_board}")" ]]; then
              set_board="lepotato"
          fi
          echo "ARMBIAN_BOARD=${set_board}" >> $GITHUB_ENV
          ARR_DESKTOP=("xfce" "budgie" "cinnamon" "gnome" "xmonad" "mate")
          set_desktop="${{ github.event.inputs.set_desktop }}"
          if [[ -z "${set_desktop}" || -z "$(echo "${ARR_DESKTOP[@]}" | grep -w "${set_desktop}")" ]]; then
              set_desktop="xfce"
          fi
          echo "ARMBIAN_DESKTOP=${set_desktop}" >> $GITHUB_ENV
      - name: Download source code
        id: down
        run: |
          git clone --depth 1 https://github.com/armbian/build.git
      - name: Compile Armbian [ ${{ env.ARMBIAN_BOARD }} ]
        id: compile
        run: |
          cd build/
          sudo chmod +x compile.sh
          sudo ./compile.sh BRANCH=${{ env.ARMBIAN_BRANCH }} RELEASE=${{ env.ARMBIAN_RELEASE }} BOARD=${{ env.ARMBIAN_BOARD }} \
                            BUILD_MINIMAL=no BUILD_DESKTOP=yes EXPERT=yes DESKTOP_ENVIRONMENT=${{ env.ARMBIAN_DESKTOP }} \
                            DESKTOP_ENVIRONMENT_CONFIG_NAME=config_basic DESKTOP_APPGROUPS_SELECTED='browsers chat desktop_tools editors email internet multimedia office' \
                            HOST=armbian KERNEL_ONLY=no KERNEL_CONFIGURE=no \
                            CLEAN_LEVEL=make,debs COMPRESS_OUTPUTIMAGE=sha
          echo "::set-output name=status::success"
      - name: Rebuild Armbian for Amlogic s9xxx
        uses: ophub/amlogic-s9xxx-armbian@main
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          build_target: armbian
          armbian_path: build/output/images/*.img
          armbian_soc: ${{ github.event.inputs.armbian_soc }}_${{ github.event.inputs.set-desktop }}
          armbian_kernel: ${{ github.event.inputs.armbian_kernel }}
          armbian_size: ${{ github.event.inputs.armbian_size }}
          armbian_fstype: ${{ github.event.inputs.armbian_fstype }}

      - name: Upload Armbian image to Release
        uses: ncipollo/release-action@main
        if: env.PACKAGED_STATUS == 'success' && !cancelled()
        with:
          tag: Armbian_Aml_${{ env.ARMBIAN_RELEASE }}_${{ env.ARMBIAN_DESKTOP }}_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is Armbian image with ${{ env.ARMBIAN_DESKTOP }} desktop (basic_config) for Amlogic s9xxx tv box
            * Firmware information
            Default username: root
            Default password: 1234
            Install command: armbian-install
            Update command: armbian-update
